--- #YAML:1.0
name:                List-Member
version:             0.044
abstract:            PROLOG's member/2: return index of  in @y.
license:             ~
author:              
    - Lee Goddard <lgoddard-at-cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
