--- #YAML:1.0
name:                List-Member
version:             0.043
abstract:            PROLOG's member/2: return index of  in @y.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Lee Goddard <lgoddard-at-cpan.org>
